# Generated by Django 4.2.6 on 2023-11-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_booking_id_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
